### PR TITLE
Testing

### LINKED ISSUE #42: `lingo run` returns with `- Main: Success` even when the program exits with error
```
target C;

main reactor {
    reaction (startup)  {=
        lf_print("Hello World!");
        lf_print_error_and_exit("ERROR");
    =}
} 
```

Yields:

```
Running "/home/erling/dev/lf/lingo/tmp/c/target/bin/Main"
FATAL ERROR: ERROR
---- Start execution at time Tue Oct 10 17:15:55 2023
---- plus 538501132 nanoseconds
Environment 0: ---- Spawning 1 workers.
Hello World!
---- Terminating environment 0
---- Elapsed logical time (in nsec): 0
---- Elapsed physical time (in nsec): 235,323
- Main: Success
```

### PR DESCRIPTION
**Pull request by tanneberger**
# Things Done

- CI
    - Running Tests for CPP, NPM and LFC backends
- Fixed a lot of bugs that were discovered by the ci
- Added the `keep-alive` flag 

# Future Work

- Typescript: Building of Federations
- Typescript: Serialization
- Cpp: Fixing Include Paths
- Race Condition when using parallel builds: Compiling of sources potentially starts before src-gen finishes

Fixes #42.

### CODE REVIEW

File: test.sh
Comment (lhstrh) [inline test.sh:1]: What is this file for? It looks outdated and not used anywhere...

File: .github/workflows/sandbox.yaml [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+          override: true
+      - id: get-release
+        name: get-latest-release
+        uses: pozetroninc/github-action-get-latest-release@master
+        with:
+          repository: lf-lang/lingua-franca
+      - name: Integration Test
+        run: |
+            # uninstalling java11 and installing java17
+            sudo apt remove openjdk-11-jre-headless
```
Comment (lhstrh) [inline .github/workflows/sandbox.yaml:27]: The first half of these commands can be replaced by:
```
 - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
```

File: .github/workflows/sandbox.yaml [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    branches:
+      - master
+
+name: Sandbox
+jobs:
+  check:
+    name: Sandbox
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
```
Comment (lhstrh) [inline .github/workflows/sandbox.yaml:13]:
```suggestion
      - uses: actions/checkout@v3
```

File: .github/workflows/sandbox.yaml [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+      - uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          override: true
+      - id: get-release
```
Comment (lhstrh) [inline .github/workflows/sandbox.yaml:19]: It doesn't look like the output of this action is used anywhere?

File: .github/workflows/sandbox.yaml [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+            sudo apt install openjdk-17-jre-headless
+            
+            # setting java17
+            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
+            
+            # building lingo
+            cargo b --release
+
+            # installing lingua-franca tests           
+            git clone https://github.com/lf-lang/lingua-franca.git ./lf-test
```
Comment (lhstrh) [inline .github/workflows/sandbox.yaml:39]: This is probably where we want to check out the latest release...

Comment (lhstrh) [reply .github/workflows/sandbox.yaml:39]: I prefer the directory to just be `lingua-franca`. There is already a `test` directory in there...

**Review by lhstrh — COMMENTED** [review]
This generally looks good. But I provided some feedback. I prefer to call the default CI workflow to be named `ci.yml`, but that's a personal preference...

File: .github/workflows/sandbox.yaml (hunk 1 above)
Comment (revol-xut) [reply .github/workflows/sandbox.yaml]: done

File: .github/workflows/sandbox.yaml (hunk 3 above)
Comment (revol-xut) [reply .github/workflows/sandbox.yaml]: done

File: .github/workflows/sandbox.yaml (hunk 4 above)
Comment (revol-xut) [reply .github/workflows/sandbox.yaml]: done

File: .github/workflows/sandbox.yaml (hunk 2 above)
Comment (revol-xut) [reply .github/workflows/sandbox.yaml]: done

File: .gitignore [hunk 5]
```diff
@@ -19,3 +19,4 @@ sandbox/
 build/
 **/src-gen/
 tmp/
+lf-test
```
Comment (lhstrh) [inline .gitignore:22]:
```suggestion
lingua-franca
```

File: test.sh
Comment (lhstrh) [inline test.sh:1]: Remove this?

**Review by lhstrh — CHANGES_REQUESTED** [review]

**Review by lhstrh — COMMENTED** [review]
Looks like we only test C++? Shouldn't we test all targets?

**Comment by revol-xut** [comment]
Regarding Testing different targets, I would say we do this on a per-backend basis so we would have tests for cmake, npm, pnpm and lfc

**Comment by revol-xut** [comment]
I would add the other backends tests in a seperate pr

**Review by lhstrh — COMMENTED** [review]
This looks good to me, but, needless to say, we still have test failures...

**Comment by revol-xut** [comment]
The CPP Tests are failing becuase the wrong path is in 
LF_SRC_PKG_PATH:UNINITIALIZED=/home/revol-xut/workspace/lf/lingua-franca/test

It should always point to the src dir

File: .github/workflows/ci.yaml [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+
+        shell: bash
+  lfc-test:
+    name: LFC Fallback Test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Setup
+        uses: ./.github/actions/environment
+      - name: Integration Test TypeScript
```
Comment (lhstrh) [inline .github/workflows/ci.yaml:48]: Why is this using TypeScript though? What about other targets?

File: test/Lingo-LFC.toml [hunk 7]
```diff
@@ -0,0 +1,360 @@
+[package]
+name = "LFC-Tests"
+version = "0.2.0"
```
Comment (lhstrh) [inline test/Lingo-LFC.toml:3]:
```suggestion
version = "0.1.0"
```

File: test/Lingo-TypeScript.toml [hunk 8]
```diff
@@ -0,0 +1,1071 @@
...
+main_reactor = "TypeScript/src/StructScale.lf"
+
+[app.dependencies]
+
+[app.properties]
+
+[[app]]
+target = "TypeScript"
+platform = "Native"
+main_reactor = "TypeScript/src/TestForPreviousOutput.lf"
```
Comment (lhstrh) [inline test/Lingo-TypeScript.toml:481]: Should we just call this `main`?

Comment (revol-xut) [reply test/Lingo-TypeScript.toml:481]: would make it more tidily n my opinion

File: test/Lingo-LFC.toml (hunk 7 above)
Comment (revol-xut) [reply test/Lingo-LFC.toml:3]: yes

File: .github/actions/environment/action.yaml [hunk 9]
```diff
@@ -0,0 +1,39 @@
...
+          # export JAVA_HOME=/usr/lib/jvm/java-17-temurin-amd64
+          
+          # building lingo
+          cargo b --release
+
+          # installing lingua-franca tests           
+          git clone https://github.com/lf-lang/lingua-franca.git ./lingua-franca
+          
+          # installing lfc
+          curl -Ls https://install.lf-lang.org | bash -s cli
```
Comment (lhstrh) [inline .github/actions/environment/action.yaml:29]:
```suggestion
          curl -Ls https://install.lf-lang.org | bash -s nightly cli
```

**Comment by tanneberger** [comment]
@lhstrh Last Thing I did this weekend was looking into why the typescript CI is still red, and I think its the dockerized tests.

**Comment by tanneberger** [comment]
Okay the next problem with the typescript target is that the federated code gen is dropped under `fed-gen` and not `src-gen`

**Comment by lhstrh** [comment]
> Okay, the next problem with the typescript target is that the federated code gen is dropped under `fed-gen` and not `src-gen`. Is the `fed-gen` folder so structurally different from the `src-gen` folder that its not feasible to remove the `fed-gen` folder ? @lhstrh

Yes, it is. The `fed-gen/src` folder actually has generated LF code in it, which is then compiled down to target code in a second step.

**Comment by tanneberger** [comment]
@lhstrh Would it be possible to rename `fed-gen` to `src-gen`

File: test/Lingo-TypeScript.toml (hunk 8 above)
Comment (lhstrh) [reply test/Lingo-TypeScript.toml:481]: :+1: Could you make the change?

File: .github/actions/environment/action.yaml (hunk 9 above)
Comment (lhstrh) [reply .github/actions/environment/action.yaml:29]: How is it able to pass the tests with the latest release? Changes in the `json` parsing happened later and are only available in `nightly` yet.

File: test/Lingo-LFC.toml
Comment (lhstrh) [inline test/Lingo-LFC.toml:1]: Should this be `Lingo-C.toml`?

File: test/Lingo-TypeScript.toml (hunk 8 above)
Comment (tanneberger) [reply test/Lingo-TypeScript.toml]: done

File: .github/actions/environment/action.yaml (hunk 9 above)
Comment (tanneberger) [reply .github/actions/environment/action.yaml]: I changed it to nightly, this also simplified the CI because I don't need to figure out the current version of lfc and can just checkout the nightly tag in the lingua-franca repo

Comment (tanneberger) [reply .github/actions/environment/action.yaml]: => done

**Review by lhstrh — COMMENTED** [review]
This looks great! I think we should address the remaining Clippy warnings before merging though...

**Review by lhstrh — APPROVED** [review]
Was only able to do a spot check because I'm not a Rust expert, but this looks good to me!
